### ISSUE TITLE
Cannot read property 'mode' of undefined

### ISSUE THREAD

**Issue by M0in4** [Lierrmm/Node-CallOfDuty#14] opened 2020-04-02 09:25 UTC
```
TypeError: Cannot read property 'mode' of undefined
    at /home/xx/cod_server/node_modules/call-of-duty-api/index.js:186:41
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

When I try to call:
```
		API.MWwz(username, apiGame).then(data => {
			console.log(data);  // see output
			return res.status(202).json({
				"error": "nil",
				"response": data
			});
		}).catch (err => {
			console.log(err);
			return res.status(202).json({
				"error": err,
				"response": "nil"
			});
		});
```

**Comment by Lierrmm** [comment] 2020-04-02 13:30
Make sure you have the latest version with `npm i call-of-duty-api@latest`. 
This issue was fixed with the latest release.

**Comment by M0in4** [comment] 2020-04-02 19:27
I have updated to the latest update and I've got the same error

**Comment by Lierrmm** [comment] 2020-04-03 12:19
Can you send an example of the whole script you are using?

**Comment by M0in4** [comment] 2020-04-04 22:59
```
var express = require('express');
var router = express.Router();
const API = require('call-of-duty-api')();

router.get('/:username/:game', function(req, res, next) {
	var username = req.params.username;
	var game = req.params.game;
	var apiGame = API.platforms.battle;
	console.log(apiGame);
	if (game == "battle") {
		apiGame = API.platforms.battle;
	}
	else if (game == "steam") {
		apiGame = API.platforms.steam;
	}
	else if (game == "psn") {
		apiGame = API.platforms.psn;
	}
	
	function receiveStats() {
		API.MWwz(username, apiGame).then(data => {
			console.log(data);  // see output
			return res.status(202).json({
				"error": "nil",
				"response": data
			});
		}).catch (err => {
			console.log(err);
			return res.status(202).json({
				"error": err,
				"response": "nil"
			});
		});
	}
	
	receiveStats();
});
module.exports = router;
```

**Comment by Lierrmm** [comment] 2020-04-06 09:45
Have you got an example user?

This is my test case which works as intended.

```javascript
const api = require('call-of-duty-api')();
const user = "Lierrmm425324";

test = () => {
    let username = user;
    let apiGame = api.platforms.battle;

    api.MWwz(username, apiGame).then(data => {
        console.log(data);  // see output
        return JSON.stringify({
            "error": "nil",
            "response": data
        });
    }).catch (err => {
        console.log(err);
        return JSON.stringify({
            "error": err,
            "response": "nil"
        });
    });
};

console.log(test());
```

### output
```javascript
[ br: {}, br_dmz: {}, br_all: {} ]
```

**Comment by M0in4** [comment] 2020-04-07 19:50
Its giving error with your username too with my code

**Comment by Lierrmm** [comment] 2020-04-08 07:28
What version of the api are you using? it will say in package.json

**Comment by M0in4** [comment] 2020-04-08 08:39
1.0.25

**Comment by Lierrmm** [comment] 2020-04-08 17:56
Hmm, Weird. 

I'd suggest doing a clean uninstall so `npm uninstall call-of-duty-api` and 
then `npm i call-of-duty-api@latest`.

**Comment by M0in4** [comment] 2020-04-08 20:53
Done, same error...
`	function receiveStats() {
		test = () => {
		    API.MWwz("Lierrmm425324", API.platforms.battle).then(data => {
		        console.log(data);  // see output
		        return JSON.stringify({
		            "error": "nil",
		            "response": data
		        });
		    }).catch (err => {
		        console.log(err);
		        return JSON.stringify({
		            "error": err,
		            "response": "nil"
		        });
		    });
		};

		console.log(test());
	}`

**Comment by Lierrmm** [comment] 2020-04-09 12:56
Can you navigate to node_modules/call-of-duty-api/index.js and go to line 187 and send a screenshot please.

**Comment by M0in4** [comment] 2020-04-09 13:13
`    module.MWwz = function (gamertag, platform = config.platform) {
        return new Promise((resolve, reject) => {
            brDetails = [];
            brDetails.br = {};
            brDetails.br_dmz = {};
            brDetails.br_all = {};
            this.MWmp(gamertag, platform).then((data) => {
                if(typeof data.lifetime.mode.br) { data.lifetime.mode.br.properties.title = "br"; brDetails.br = data.lifetime.mode.br.properties; }
                if(typeof data.lifetime.mode.br_dmz) { data.lifetime.mode.br_dmz.properties.title = "br_dmz"; brDetails.br_dmz = data.lifetime.mode.br_dmz.properties; }
                if(typeof data.lifetime.mode.br_all) { data.lifetime.mode.br_all.properties.title = "br_all"; brDetails.br_all = data.lifetime.mode.br_all.properties; }
                resolve(brDetails);
            }).catch(e => reject(e));
        });
    };

`

Line 187: `                if(typeof data.lifetime.mode.br) { data.lifetime.mode.br.properties.title = "br"; brDetails.br = data.lifetime.mode.br.properties; }`

**Comment by Lierrmm** [comment] 2020-04-09 13:25
Yes, that is not on the latest version. If you look at this line you can see the implemented fix: https://github.com/Lierrmm/Node-CallOfDuty/blob/247a5ee117f40a7f93c5cb3aeacd259fc203df72/index.js#L187

**Comment by M0in4** [comment] 2020-04-09 13:38
Is your npm updated or its updated only on GitHub?

**Comment by Lierrmm** [comment] 2020-04-09 14:49
It was updated on NPM too.

I have published it again, could you try updating it to 1.0.26 please

**Comment by M0in4** [comment] 2020-04-09 17:14
I'll try soon.
I've edited it manually for now and its retrieving null stats for all username.
Have you got some username to test with?

**Comment by Lierrmm** [comment] 2020-04-09 17:50
Lierrmm#2364

**Closed** 2020-04-14 12:07 UTC
